AWSTemplateFormatVersion: '2010-09-09'
Description: Deployment bucket

Parameters:
  BucketName:
    Type: String

Resources:
  DeployBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref BucketName