AWSTemplateFormatVersion: "2010-09-09"
Description: cloudfront for website usage csp header lambda at edge

Parameters:
  WebsiteBucketName:
    Type: String
  SecurityHeadersLambdaArn:
    Type: String

Resources:
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref 'WebsiteBucketName'
      AccessControl: BucketOwnerFullControl

  WebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref 'WebsiteBucket'
      PolicyDocument:
        Version: 2012-10-17
        Statement:
        - Sid: PublicReadForGetBucketObjects
          Effect: Allow
          Principal: '*'
          Action:
          - 's3:GetObject'
          Resource: !Sub 'arn:aws:s3:::${WebsiteBucket}/*'

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        DefaultCacheBehavior:
          ForwardedValues:
            QueryString: true
          TargetOriginId: webpage
          ViewerProtocolPolicy: redirect-to-https
          LambdaFunctionAssociations:
          - EventType: origin-response
            LambdaFunctionARN: !Ref 'SecurityHeadersLambdaArn'
        DefaultRootObject: index.html
        Enabled: true
        Origins:
        - DomainName: !GetAtt 'WebsiteBucket.DomainName'
          Id: webpage
          S3OriginConfig:
            OriginAccessIdentity:
              Ref: AWS::NoValue
        PriceClass: PriceClass_100
