AWSTemplateFormatVersion: '2010-09-09'
Description: Post csp report function
Globals:
  Api:
    Cors: '''*'''
Outputs:
  CSPReportEndpoint:
    Description: The endpoint for the CSP reporting lambda
    Value:
      Fn::Sub: https://${RestApi}.execute-api.${AWS::Region}.amazonaws.com/${RestApi.Stage}
Resources:
  EsCluster:
    Properties:
      AccessPolicies:
        Statement:
        - Action: es:*
          Effect: Allow
          Principal:
            AWS: arn:aws:iam::569769687575:user/kevin
          Resource: arn:aws:es:eu-west-1:569769687575:domain/test/*
        Version: '2012-10-17'
      EBSOptions:
        EBSEnabled: true
        Iops: 0
        VolumeSize: 20
        VolumeType: gp2
      ElasticsearchClusterConfig:
        InstanceCount: '1'
        InstanceType: t2.small.elasticsearch
      ElasticsearchVersion: '6.3'
    Type: AWS::Elasticsearch::Domain
  LambdaPermission:
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Ref: PostCSPReport
      Principal: apigateway.amazonaws.com
    Type: AWS::Lambda::Permission
  PostCSPReport:
    Properties:
      CodeUri: s3://binx-csp-provider/421d241bce2458ff3476822aa50d37b9
      Environment:
        Variables:
          DOMAIN_ENDPOINT:
            Fn::GetAtt:
            - EsCluster
            - DomainEndpoint
          REGION: eu-west-1
      Events:
        PostReportEvent:
          Properties:
            Method: post
            Path: /postreport
            RestApiId: RestApi
          Type: Api
      Handler: csp_report_indexer.handler
      Runtime: python3.7
      Timeout: 30
    Type: AWS::Serverless::Function
  RestApi:
    Properties:
      StageName: dev
    Type: AWS::Serverless::Api
Transform: AWS::Serverless-2016-10-31
