AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Post csp report function

Globals:
  Api:
    Cors: "'*'"

Resources:
  RestApi:
    Type: 'AWS::Serverless::Api'
    Properties:
      StageName: dev
  LambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref PostCSPReport
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
  PostCSPReport:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: csp_report_indexer.handler
      Runtime: python3.7
      Timeout: 30
      CodeUri:
      Environment:
        Variables:
          DOMAIN_ENDPOINT: !GetAtt EsCluster.DomainEndpoint
          REGION: 'eu-west-1'
      Events:
        PostReportEvent:
          Type: Api
          Properties:
            Path: /postreport
            Method: post
            RestApiId: RestApi

  EsCluster:
    Type: AWS::Elasticsearch::Domain
    Properties:
      ElasticsearchVersion: '6.3'
      ElasticsearchClusterConfig:
        InstanceCount: '1'
        InstanceType: 't2.small.elasticsearch'
      EBSOptions:
        EBSEnabled: true
        Iops: 0
        VolumeSize: 20
        VolumeType: 'gp2'
      AccessPolicies:
        Version: '2012-10-17'
        Statement:
        -
          Effect: 'Allow'
          Principal:
            AWS: 'arn:aws:iam::569769687575:user/kevin'
          Action: 'es:*'
          Resource: 'arn:aws:es:eu-west-1:569769687575:domain/test/*'

Outputs:
  CSPReportEndpoint:
    Description: 'The endpoint for the CSP reporting lambda'
    Value: !Sub 'https://${RestApi}.execute-api.${AWS::Region}.amazonaws.com/${RestApi.Stage}'